CREATE DATABASE IF NOT EXISTS banco_teste;

USE banco_teste;

CREATE TABLE IF NOT EXISTS `animal` (
  `idAnimal` INT AUTO_INCREMENT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
);